import TsComment from './TsComment.tsx';

export default function TypespecGenerationComment() {
  return <TsComment literal="// WARNING: This file is auto-generated by Typespec. Do not edit this file directly." />;
}
